//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMobileApp.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public Attachment()
        {
            this.ShopPictures = new HashSet<ShopPicture>();
            this.ServiceAttachments = new HashSet<ServiceAttachment>();
            this.CarPictures = new HashSet<CarPicture>();
            this.ProfilePictures = new HashSet<ProfilePicture>();
            this.DealerPictures = new HashSet<DealerPicture>();
        }
    
        public long AttachmentId { get; set; }
        public string AttachmentFileName { get; set; }
        public string ContentType { get; set; }
        public string FileSource { get; set; }
        public byte[] FileBinary { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
    
        public virtual ICollection<ShopPicture> ShopPictures { get; set; }
        public virtual ICollection<ServiceAttachment> ServiceAttachments { get; set; }
        public virtual ICollection<CarPicture> CarPictures { get; set; }
        public virtual ICollection<ProfilePicture> ProfilePictures { get; set; }
        public virtual ICollection<DealerPicture> DealerPictures { get; set; }
    }
}
