//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMobileApp.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerRating
    {
        public long DealerRatingsId { get; set; }
        public long DealerProfileId { get; set; }
        public int Rating { get; set; }
        public long UserProfileId { get; set; }
        public Nullable<System.DateTime> RatedOn { get; set; }
        public string RatingDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual DealerProfile DealerProfile { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
