//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMobileApp.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceStatusType
    {
        public ServiceStatusType()
        {
            this.ServiceStatus = new HashSet<ServiceStatu>();
        }
    
        public int ServiceStatusTypeID { get; set; }
        public string ServiceStatusTypeCode { get; set; }
        public string ServiceStatusTypeDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<ServiceStatu> ServiceStatus { get; set; }
    }
}
