//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMobileApp.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDescriptionType
    {
        public ServiceDescriptionType()
        {
            this.ServiceDescriptions = new HashSet<ServiceDescription>();
        }
    
        public int ServiceDescriptionTypeId { get; set; }
        public string ServiceDescriptionTypeCode { get; set; }
        public string ServiceDescriptionType1 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<ServiceDescription> ServiceDescriptions { get; set; }
    }
}
