//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMobileApp.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        public ServiceRequest()
        {
            this.ServiceAttachments = new HashSet<ServiceAttachment>();
            this.ServiceDescriptions = new HashSet<ServiceDescription>();
            this.ServiceStatus = new HashSet<ServiceStatu>();
        }
    
        public long ServiceRequestId { get; set; }
        public string ServiceRequestNo { get; set; }
        public long DealerProfileId { get; set; }
        public long CarDetailsId { get; set; }
        public long UserProfileId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.TimeSpan AppointmentTime { get; set; }
        public Nullable<System.DateTime> AppointmentRequestDate { get; set; }
        public Nullable<System.DateTime> AppointmentAcceptedOn { get; set; }
        public Nullable<System.DateTime> ServiceDeliveredOn { get; set; }
        public Nullable<bool> IsPickupDropAvailable { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual DealerProfile DealerProfile { get; set; }
        public virtual ICollection<ServiceAttachment> ServiceAttachments { get; set; }
        public virtual ICollection<ServiceDescription> ServiceDescriptions { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual CarDetail CarDetail { get; set; }
        public virtual ICollection<ServiceStatu> ServiceStatus { get; set; }
    }
}
