//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMobileApp.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.DealerProfiles = new HashSet<DealerProfile>();
            this.DealerRatings = new HashSet<DealerRating>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.CarDetails = new HashSet<CarDetail>();
            this.ProfilePictures = new HashSet<ProfilePicture>();
        }
    
        public long UserProfileId { get; set; }
        public string UserQualifier { get; set; }
        public string UserPassword { get; set; }
        public string OneTimePassword { get; set; }
        public int UserTypeId { get; set; }
        public Nullable<System.DateTime> LastLoginOn { get; set; }
        public string UserName { get; set; }
        public string UserMobileNumber { get; set; }
        public string UserEmail { get; set; }
        public Nullable<bool> IsPromotionalEmailRequired { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<DealerProfile> DealerProfiles { get; set; }
        public virtual ICollection<DealerRating> DealerRatings { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual ICollection<CarDetail> CarDetails { get; set; }
        public virtual ICollection<ProfilePicture> ProfilePictures { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
