//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMobileApp.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetServiceDetails
    {
        public long ServiceRequestId { get; set; }
        public string ServiceRequestNo { get; set; }
        public long DealerProfileId { get; set; }
        public long CarDetailsId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.TimeSpan AppointmentTime { get; set; }
        public Nullable<System.DateTime> AppointmentRequestDate { get; set; }
        public Nullable<System.DateTime> AppointmentAcceptedOn { get; set; }
        public Nullable<System.DateTime> ServiceDeliveredOn { get; set; }
        public Nullable<bool> IsPickupDropAvailable { get; set; }
        public Nullable<int> ServiceDescriptionTypeId { get; set; }
        public string ServiceDescription { get; set; }
        public string ServiceDescriptionTypeCode { get; set; }
        public string ServiceDescriptionType { get; set; }
        public Nullable<int> ServiceStatusTypeId { get; set; }
        public Nullable<System.DateTime> StatusUpdatedOn { get; set; }
        public string ServiceStatusTypeCode { get; set; }
        public string ServiceStatusTypeDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress { get; set; }
        public string DealerName { get; set; }
        public string DealerEmail { get; set; }
        public Nullable<long> ShopPictureAttachmentId { get; set; }
        public string ShopPictureFileSource { get; set; }
        public Nullable<System.DateTime> ShopPictureUploadedOn { get; set; }
        public Nullable<int> CarMakeYear { get; set; }
        public string CarModelName { get; set; }
        public string CarName { get; set; }
        public Nullable<long> CarPictureAttachmentId { get; set; }
        public string CarPictureFileSource { get; set; }
        public Nullable<System.DateTime> CarPictureUploadedOn { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserMobileNumber { get; set; }
    }
}
