//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMobileApp.UnitTest.ValidateOneTimePassword {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSMobileApp.UnitTest.ValidateOneTimePassword.NotificationResource", typeof(NotificationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hash.
        /// </summary>
        internal static string Apikey_Hash {
            get {
                return ResourceManager.GetString("Apikey_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string Apikey_Message {
            get {
                return ResourceManager.GetString("Apikey_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numbers.
        /// </summary>
        internal static string Apikey_Numbers {
            get {
                return ResourceManager.GetString("Apikey_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sender.
        /// </summary>
        internal static string Apikey_Sender {
            get {
                return ResourceManager.GetString("Apikey_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string Apikey_UserName {
            get {
                return ResourceManager.GetString("Apikey_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer, your vehicle {0} service appointment got accepted by {1}..
        /// </summary>
        internal static string Msg_AcceptServiceRequest {
            get {
                return ResourceManager.GetString("Msg_AcceptServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer, {0} has cancelled the service appointment with you..
        /// </summary>
        internal static string Msg_CancelServiceRequest {
            get {
                return ResourceManager.GetString("Msg_CancelServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer, Your vehicle {0} service appointment has been cancelled by {1}..
        /// </summary>
        internal static string Msg_DealerCancellation {
            get {
                return ResourceManager.GetString("Msg_DealerCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer, Your vehicle {0} service appointment got Declined by {1}..
        /// </summary>
        internal static string Msg_DeclineServiceRequest {
            get {
                return ResourceManager.GetString("Msg_DeclineServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer, your vehicle {0} got delivered by {1}.
        /// </summary>
        internal static string Msg_Delivered {
            get {
                return ResourceManager.GetString("Msg_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYPCIE OTP {0}. Welcome to GYPCIE, Your ultimate car mate !.
        /// </summary>
        internal static string Msg_OneTimePassword {
            get {
                return ResourceManager.GetString("Msg_OneTimePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer, your vehicle {0} is ready for delivery in {1}.
        /// </summary>
        internal static string Msg_ReadyForDelivery {
            get {
                return ResourceManager.GetString("Msg_ReadyForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully. New password for the application is {0}.
        /// </summary>
        internal static string Msg_ResetPassword {
            get {
                return ResourceManager.GetString("Msg_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer, your vehicle {0} is under work in progress in {1}.
        /// </summary>
        internal static string Msg_WorkInProgress {
            get {
                return ResourceManager.GetString("Msg_WorkInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmsApiHashKey.
        /// </summary>
        internal static string SmsApiHashKey {
            get {
                return ResourceManager.GetString("SmsApiHashKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmsApiTemplateUrl.
        /// </summary>
        internal static string SmsApiTemplateUrl {
            get {
                return ResourceManager.GetString("SmsApiTemplateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmsApiUrl.
        /// </summary>
        internal static string SmsApiUrl {
            get {
                return ResourceManager.GetString("SmsApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmsInternationalApiHashKey.
        /// </summary>
        internal static string SmsInternationalApiHashKey {
            get {
                return ResourceManager.GetString("SmsInternationalApiHashKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmsInternationalApiUrl.
        /// </summary>
        internal static string SmsInternationalApiUrl {
            get {
                return ResourceManager.GetString("SmsInternationalApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmsInternationalApiUsername.
        /// </summary>
        internal static string SmsInternationalApiUsername {
            get {
                return ResourceManager.GetString("SmsInternationalApiUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmsInternationalSender.
        /// </summary>
        internal static string SmsInternationalSender {
            get {
                return ResourceManager.GetString("SmsInternationalSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmsSender.
        /// </summary>
        internal static string SmsSender {
            get {
                return ResourceManager.GetString("SmsSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmsUsername.
        /// </summary>
        internal static string SmsUsername {
            get {
                return ResourceManager.GetString("SmsUsername", resourceCulture);
            }
        }
    }
}
