//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMobileApp.DataProcess.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataProcessResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataProcessResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSMobileApp.DataProcess.Resource.DataProcessResource", typeof(DataProcessResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AppointmentDate.
        /// </summary>
        internal static string spparam_AppointmentDate {
            get {
                return ResourceManager.GetString("spparam_AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AppointmentRequestDate.
        /// </summary>
        internal static string spparam_AppointmentRequestDate {
            get {
                return ResourceManager.GetString("spparam_AppointmentRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AppointmentTime.
        /// </summary>
        internal static string spparam_AppointmentTime {
            get {
                return ResourceManager.GetString("spparam_AppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttachmentFileName.
        /// </summary>
        internal static string spparam_AttachmentFileName {
            get {
                return ResourceManager.GetString("spparam_AttachmentFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttachmentId.
        /// </summary>
        internal static string spparam_AttachmentId {
            get {
                return ResourceManager.GetString("spparam_AttachmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttachmentIds.
        /// </summary>
        internal static string spparam_AttachmentIds {
            get {
                return ResourceManager.GetString("spparam_AttachmentIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AuthorizedDealershipName.
        /// </summary>
        internal static string spparam_AuthorizedDealershipName {
            get {
                return ResourceManager.GetString("spparam_AuthorizedDealershipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BusinessNatureTypeId.
        /// </summary>
        internal static string spparam_BusinessNatureTypeId {
            get {
                return ResourceManager.GetString("spparam_BusinessNatureTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BusinessTypeId.
        /// </summary>
        internal static string spparam_BusinessTypeId {
            get {
                return ResourceManager.GetString("spparam_BusinessTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CancelReason.
        /// </summary>
        internal static string spparam_CancelReason {
            get {
                return ResourceManager.GetString("spparam_CancelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cardetailsid.
        /// </summary>
        internal static string spparam_cardetailsid {
            get {
                return ResourceManager.GetString("spparam_cardetailsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CarDisplayName.
        /// </summary>
        internal static string spparam_CarDisplayName {
            get {
                return ResourceManager.GetString("spparam_CarDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @carmakeyear.
        /// </summary>
        internal static string spparam_carmakeyear {
            get {
                return ResourceManager.GetString("spparam_carmakeyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CarModelName.
        /// </summary>
        internal static string spparam_CarModelName {
            get {
                return ResourceManager.GetString("spparam_CarModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @carname.
        /// </summary>
        internal static string spparam_carname {
            get {
                return ResourceManager.GetString("spparam_carname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @carnumber.
        /// </summary>
        internal static string spparam_carnumber {
            get {
                return ResourceManager.GetString("spparam_carnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CarTrackingId.
        /// </summary>
        internal static string spparam_CarTrackingId {
            get {
                return ResourceManager.GetString("spparam_CarTrackingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ContentType.
        /// </summary>
        internal static string spparam_ContentType {
            get {
                return ResourceManager.GetString("spparam_ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CurrentDate.
        /// </summary>
        internal static string spparam_CurrentDate {
            get {
                return ResourceManager.GetString("spparam_CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CurrentLatitude.
        /// </summary>
        internal static string spparam_CurrentLatitude {
            get {
                return ResourceManager.GetString("spparam_CurrentLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CurrentLongitude.
        /// </summary>
        internal static string spparam_CurrentLongitude {
            get {
                return ResourceManager.GetString("spparam_CurrentLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DealerProfileId.
        /// </summary>
        internal static string spparam_DealerProfileId {
            get {
                return ResourceManager.GetString("spparam_DealerProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DealerRatingsId.
        /// </summary>
        internal static string spparam_DealerRatingsId {
            get {
                return ResourceManager.GetString("spparam_DealerRatingsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DeviceId.
        /// </summary>
        internal static string spparam_DeviceId {
            get {
                return ResourceManager.GetString("spparam_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FileBinary.
        /// </summary>
        internal static string spparam_FileBinary {
            get {
                return ResourceManager.GetString("spparam_FileBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FileName.
        /// </summary>
        internal static string spparam_FileName {
            get {
                return ResourceManager.GetString("spparam_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FileSource.
        /// </summary>
        internal static string spparam_FileSource {
            get {
                return ResourceManager.GetString("spparam_FileSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @GoogleApiKey.
        /// </summary>
        internal static string spparam_GoogleApiKey {
            get {
                return ResourceManager.GetString("spparam_GoogleApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @InspectionDescription.
        /// </summary>
        internal static string spparam_InspectionDescription {
            get {
                return ResourceManager.GetString("spparam_InspectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IsCompanyOwned.
        /// </summary>
        internal static string spparam_IsCompanyOwned {
            get {
                return ResourceManager.GetString("spparam_IsCompanyOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IsHavingOffers.
        /// </summary>
        internal static string spparam_IsHavingOffers {
            get {
                return ResourceManager.GetString("spparam_IsHavingOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IsMultiBrand.
        /// </summary>
        internal static string spparam_IsMultiBrand {
            get {
                return ResourceManager.GetString("spparam_IsMultiBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IsPickupDropAvailable.
        /// </summary>
        internal static string spparam_IsPickupDropAvailable {
            get {
                return ResourceManager.GetString("spparam_IsPickupDropAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IsPickupDropFacilityAvailable.
        /// </summary>
        internal static string spparam_IsPickupDropFacilityAvailable {
            get {
                return ResourceManager.GetString("spparam_IsPickupDropFacilityAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IsPromotionalEmailRequired.
        /// </summary>
        internal static string spparam_IsPromotionalEmailRequired {
            get {
                return ResourceManager.GetString("spparam_IsPromotionalEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Latitude.
        /// </summary>
        internal static string spparam_Latitude {
            get {
                return ResourceManager.GetString("spparam_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Longitude.
        /// </summary>
        internal static string spparam_Longitude {
            get {
                return ResourceManager.GetString("spparam_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @NewPassword.
        /// </summary>
        internal static string spparam_NewPassword {
            get {
                return ResourceManager.GetString("spparam_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @OfferDescription.
        /// </summary>
        internal static string spparam_OfferDescription {
            get {
                return ResourceManager.GetString("spparam_OfferDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @OfferDetailsId.
        /// </summary>
        internal static string spparam_OfferDetailsId {
            get {
                return ResourceManager.GetString("spparam_OfferDetailsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @OfferEndDate.
        /// </summary>
        internal static string spparam_OfferEndDate {
            get {
                return ResourceManager.GetString("spparam_OfferEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @OfferStartDate.
        /// </summary>
        internal static string spparam_OfferStartDate {
            get {
                return ResourceManager.GetString("spparam_OfferStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @OldPassword.
        /// </summary>
        internal static string spparam_OldPassword {
            get {
                return ResourceManager.GetString("spparam_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @OneTimePassword.
        /// </summary>
        internal static string spparam_OneTimePassword {
            get {
                return ResourceManager.GetString("spparam_OneTimePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PeriodicMaintenanceDescription.
        /// </summary>
        internal static string spparam_PeriodicMaintenanceDescription {
            get {
                return ResourceManager.GetString("spparam_PeriodicMaintenanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PinCode.
        /// </summary>
        internal static string spparam_PinCode {
            get {
                return ResourceManager.GetString("spparam_PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Rating.
        /// </summary>
        internal static string spparam_Rating {
            get {
                return ResourceManager.GetString("spparam_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RatingDescription.
        /// </summary>
        internal static string spparam_RatingDescription {
            get {
                return ResourceManager.GetString("spparam_RatingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SenderId.
        /// </summary>
        internal static string spparam_SenderId {
            get {
                return ResourceManager.GetString("spparam_SenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ServiceRequestId.
        /// </summary>
        internal static string spparam_ServiceRequestId {
            get {
                return ResourceManager.GetString("spparam_ServiceRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ServiceStatusTypeId.
        /// </summary>
        internal static string spparam_ServiceStatusTypeId {
            get {
                return ResourceManager.GetString("spparam_ServiceStatusTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ShopAddress.
        /// </summary>
        internal static string spparam_ShopAddress {
            get {
                return ResourceManager.GetString("spparam_ShopAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ShopName.
        /// </summary>
        internal static string spparam_ShopName {
            get {
                return ResourceManager.GetString("spparam_ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SpecificationDescription.
        /// </summary>
        internal static string spparam_SpecificationDescription {
            get {
                return ResourceManager.GetString("spparam_SpecificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserEmail.
        /// </summary>
        internal static string spparam_UserEmail {
            get {
                return ResourceManager.GetString("spparam_UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserMobileNumber.
        /// </summary>
        internal static string spparam_UserMobileNumber {
            get {
                return ResourceManager.GetString("spparam_UserMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserName.
        /// </summary>
        internal static string spparam_UserName {
            get {
                return ResourceManager.GetString("spparam_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserPassword.
        /// </summary>
        internal static string spparam_UserPassword {
            get {
                return ResourceManager.GetString("spparam_UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserProfileId.
        /// </summary>
        internal static string spparam_UserProfileId {
            get {
                return ResourceManager.GetString("spparam_UserProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserQualifier.
        /// </summary>
        internal static string spparam_UserQualifier {
            get {
                return ResourceManager.GetString("spparam_UserQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserTypeID.
        /// </summary>
        internal static string spparam_UserTypeId {
            get {
                return ResourceManager.GetString("spparam_UserTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServiceInfo].[usp_CancelServiceRequestByDealer].
        /// </summary>
        internal static string usp_CancelServiceRequestByDealer {
            get {
                return ResourceManager.GetString("usp_CancelServiceRequestByDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_ChangePassword].
        /// </summary>
        internal static string usp_ChangePassword {
            get {
                return ResourceManager.GetString("usp_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_CheckOneTimePassword].
        /// </summary>
        internal static string usp_CheckOneTimePassword {
            get {
                return ResourceManager.GetString("usp_CheckOneTimePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_CreateDealerRatings].
        /// </summary>
        internal static string usp_CreateDealerRatings {
            get {
                return ResourceManager.GetString("usp_CreateDealerRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServiceInfo].[usp_DealerServiceHistory].
        /// </summary>
        internal static string usp_DealerServiceHistory {
            get {
                return ResourceManager.GetString("usp_DealerServiceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [WagonStation].[usp_DeleteAttachmentById].
        /// </summary>
        internal static string usp_DeleteAttachmentById {
            get {
                return ResourceManager.GetString("usp_DeleteAttachmentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_DeleteCardetailsbyId].
        /// </summary>
        internal static string usp_DeleteCardetailsbyId {
            get {
                return ResourceManager.GetString("usp_DeleteCardetailsbyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_DeleteDealerRatings].
        /// </summary>
        internal static string usp_DeleteDealerRatings {
            get {
                return ResourceManager.GetString("usp_DeleteDealerRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_DeleteOfferDetails].
        /// </summary>
        internal static string usp_DeleteOfferDetails {
            get {
                return ResourceManager.GetString("usp_DeleteOfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_DeleteProfilePicture].
        /// </summary>
        internal static string usp_DeleteProfilePicture {
            get {
                return ResourceManager.GetString("usp_DeleteProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_DeleteShopPicture].
        /// </summary>
        internal static string usp_DeleteShopPicture {
            get {
                return ResourceManager.GetString("usp_DeleteShopPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].usp_FilterDealerDetails.
        /// </summary>
        internal static string usp_FilterDealerDetails {
            get {
                return ResourceManager.GetString("usp_FilterDealerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_ForgotPassword].
        /// </summary>
        internal static string usp_ForgotPassword {
            get {
                return ResourceManager.GetString("usp_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServiceInfo].[usp_GetActiveServicesByUserProfileId].
        /// </summary>
        internal static string usp_GetActiveServicesByUserProfileId {
            get {
                return ResourceManager.GetString("usp_GetActiveServicesByUserProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [WagonStation].[usp_GetAttachmentById].
        /// </summary>
        internal static string usp_GetAttachmentById {
            get {
                return ResourceManager.GetString("usp_GetAttachmentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_GetCarDetailsbyId].
        /// </summary>
        internal static string usp_GetCarDetailsbyId {
            get {
                return ResourceManager.GetString("usp_GetCarDetailsbyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_GetCarDetailsbyUserprofileId].
        /// </summary>
        internal static string usp_GetCarDetailsbyUserprofileId {
            get {
                return ResourceManager.GetString("usp_GetCarDetailsbyUserprofileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_GetDealerDetailsByDistance].
        /// </summary>
        internal static string usp_GetDealerDetailsByDistance {
            get {
                return ResourceManager.GetString("usp_GetDealerDetailsByDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServiceInfo].[usp_GetDealerPendingForAction].
        /// </summary>
        internal static string usp_GetDealerPendingForAction {
            get {
                return ResourceManager.GetString("usp_GetDealerPendingForAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServiceInfo].[usp_GetDealerPendingForActionByUserProfileId].
        /// </summary>
        internal static string usp_GetDealerPendingForActionByUserProfileId {
            get {
                return ResourceManager.GetString("usp_GetDealerPendingForActionByUserProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServiceInfo].[usp_GetDealerPendingForApproval].
        /// </summary>
        internal static string usp_GetDealerPendingForApproval {
            get {
                return ResourceManager.GetString("usp_GetDealerPendingForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServiceInfo].[usp_GetDealerPendingForApprovalByUserProfileId].
        /// </summary>
        internal static string usp_GetDealerPendingForApprovalByUserProfileId {
            get {
                return ResourceManager.GetString("usp_GetDealerPendingForApprovalByUserProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_GetDealerProfileById].
        /// </summary>
        internal static string usp_GetDealerProfileById {
            get {
                return ResourceManager.GetString("usp_GetDealerProfileById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_GetDealerRatingByDealerProfileId].
        /// </summary>
        internal static string usp_GetDealerRatingByDealerProfileId {
            get {
                return ResourceManager.GetString("usp_GetDealerRatingByDealerProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_GetOfferDetailsByDealerProfileId].
        /// </summary>
        internal static string usp_GetOfferDetailsByDealerProfileId {
            get {
                return ResourceManager.GetString("usp_GetOfferDetailsByDealerProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_GetOfferDetailsById].
        /// </summary>
        internal static string usp_GetOfferDetailsById {
            get {
                return ResourceManager.GetString("usp_GetOfferDetailsById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_GetOfferDetailsByUserProfileId].
        /// </summary>
        internal static string usp_GetOfferDetailsByUserProfileId {
            get {
                return ResourceManager.GetString("usp_GetOfferDetailsByUserProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServiceInfo].[usp_GetUserServiceHistory].
        /// </summary>
        internal static string usp_GetUserServiceHistory {
            get {
                return ResourceManager.GetString("usp_GetUserServiceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_IsMobileNumberRegistered].
        /// </summary>
        internal static string usp_IsMobileNumberRegistered {
            get {
                return ResourceManager.GetString("usp_IsMobileNumberRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_ManageCarDetails].
        /// </summary>
        internal static string usp_ManageCarDetails {
            get {
                return ResourceManager.GetString("usp_ManageCarDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_ManageDealerProfile].
        /// </summary>
        internal static string usp_ManageDealerProfile {
            get {
                return ResourceManager.GetString("usp_ManageDealerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_ManageOfferDetails].
        /// </summary>
        internal static string usp_ManageOfferDetails {
            get {
                return ResourceManager.GetString("usp_ManageOfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [WagonStation].[usp_ManagePicture].
        /// </summary>
        internal static string usp_ManagePicture {
            get {
                return ResourceManager.GetString("usp_ManagePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_ManageProfilePicture].
        /// </summary>
        internal static string usp_ManageProfilePicture {
            get {
                return ResourceManager.GetString("usp_ManageProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServiceInfo].[usp_ManageServiceRequest].
        /// </summary>
        internal static string usp_ManageServiceRequest {
            get {
                return ResourceManager.GetString("usp_ManageServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServiceInfo].[usp_ManageServiceStatus].
        /// </summary>
        internal static string usp_ManageServiceStatus {
            get {
                return ResourceManager.GetString("usp_ManageServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_ManageShopPicture].
        /// </summary>
        internal static string usp_ManageShopPicture {
            get {
                return ResourceManager.GetString("usp_ManageShopPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_ManageUserProfile].
        /// </summary>
        internal static string usp_ManageUserProfile {
            get {
                return ResourceManager.GetString("usp_ManageUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_ResendOneTimePassword].
        /// </summary>
        internal static string usp_ResendOneTimePassword {
            get {
                return ResourceManager.GetString("usp_ResendOneTimePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_SortDealerDetailsByDistance].
        /// </summary>
        internal static string usp_SortDealerDetailsByDistance {
            get {
                return ResourceManager.GetString("usp_SortDealerDetailsByDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DealerInfo].[usp_SortDealerDetailsByRatings].
        /// </summary>
        internal static string usp_SortDealerDetailsByRatings {
            get {
                return ResourceManager.GetString("usp_SortDealerDetailsByRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_UpdateMobileNumber].
        /// </summary>
        internal static string usp_UpdateMobileNumber {
            get {
                return ResourceManager.GetString("usp_UpdateMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_UserLandingPageDetails].
        /// </summary>
        internal static string usp_UserLandingPageDetails {
            get {
                return ResourceManager.GetString("usp_UserLandingPageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_UserLandingPageDetailsByBusinessType].
        /// </summary>
        internal static string usp_UserLandingPageDetailsByBusinessType {
            get {
                return ResourceManager.GetString("usp_UserLandingPageDetailsByBusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_UserLogin].
        /// </summary>
        internal static string usp_UserLogin {
            get {
                return ResourceManager.GetString("usp_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UserInfo].[usp_ValidateOneTimePassword].
        /// </summary>
        internal static string usp_ValidateOneTimePassword {
            get {
                return ResourceManager.GetString("usp_ValidateOneTimePassword", resourceCulture);
            }
        }
    }
}
