//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMobileApp.BusinessLogic.EntityConverter.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EntityConverterResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityConverterResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSMobileApp.BusinessLogic.EntityConverter.Resource.EntityConverterResource", typeof(EntityConverterResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppointmentAcceptedOn.
        /// </summary>
        internal static string AppointmentAcceptedOn {
            get {
                return ResourceManager.GetString("AppointmentAcceptedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppointmentDate.
        /// </summary>
        internal static string AppointmentDate {
            get {
                return ResourceManager.GetString("AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppointmentRequestDate.
        /// </summary>
        internal static string AppointmentRequestDate {
            get {
                return ResourceManager.GetString("AppointmentRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppointmentTime.
        /// </summary>
        internal static string AppointmentTime {
            get {
                return ResourceManager.GetString("AppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttachmentId.
        /// </summary>
        internal static string AttachmentId {
            get {
                return ResourceManager.GetString("AttachmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizedDealershipName.
        /// </summary>
        internal static string AuthorizedDealershipName {
            get {
                return ResourceManager.GetString("AuthorizedDealershipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessNatureTypeCode.
        /// </summary>
        internal static string BusinessNatureTypeCode {
            get {
                return ResourceManager.GetString("BusinessNatureTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessNatureTypeDescription.
        /// </summary>
        internal static string BusinessNatureTypeDescription {
            get {
                return ResourceManager.GetString("BusinessNatureTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessNatureTypeId.
        /// </summary>
        internal static string BusinessNatureTypeId {
            get {
                return ResourceManager.GetString("BusinessNatureTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessTypeCode.
        /// </summary>
        internal static string BusinessTypeCode {
            get {
                return ResourceManager.GetString("BusinessTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessTypeDescription.
        /// </summary>
        internal static string BusinessTypeDescription {
            get {
                return ResourceManager.GetString("BusinessTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessTypeId.
        /// </summary>
        internal static string BusinessTypeId {
            get {
                return ResourceManager.GetString("BusinessTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelReason.
        /// </summary>
        internal static string CancelReason {
            get {
                return ResourceManager.GetString("CancelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarDetailsid.
        /// </summary>
        internal static string CarDetailsid {
            get {
                return ResourceManager.GetString("CarDetailsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarDisplayName.
        /// </summary>
        internal static string CarDisplayName {
            get {
                return ResourceManager.GetString("CarDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carmakeyear.
        /// </summary>
        internal static string carmakeyear {
            get {
                return ResourceManager.GetString("carmakeyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarModelName.
        /// </summary>
        internal static string CarModelName {
            get {
                return ResourceManager.GetString("CarModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carname.
        /// </summary>
        internal static string carname {
            get {
                return ResourceManager.GetString("carname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarPictureAttachmentId.
        /// </summary>
        internal static string CarPictureAttachmentId {
            get {
                return ResourceManager.GetString("CarPictureAttachmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarPictureContentType.
        /// </summary>
        internal static string CarPictureContentType {
            get {
                return ResourceManager.GetString("CarPictureContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarPictureFileBinary.
        /// </summary>
        internal static string CarPictureFileBinary {
            get {
                return ResourceManager.GetString("CarPictureFileBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarPictureFileName.
        /// </summary>
        internal static string CarPictureFileName {
            get {
                return ResourceManager.GetString("CarPictureFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarPictureFileSource.
        /// </summary>
        internal static string CarPictureFileSource {
            get {
                return ResourceManager.GetString("CarPictureFileSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarPictureUploadedOn.
        /// </summary>
        internal static string CarPictureUploadedOn {
            get {
                return ResourceManager.GetString("CarPictureUploadedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarTrackingId.
        /// </summary>
        internal static string CarTrackingId {
            get {
                return ResourceManager.GetString("CarTrackingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentType.
        /// </summary>
        internal static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DealerProfileId.
        /// </summary>
        internal static string DealerProfileId {
            get {
                return ResourceManager.GetString("DealerProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DealerRatingsId.
        /// </summary>
        internal static string DealerRatingsId {
            get {
                return ResourceManager.GetString("DealerRatingsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceId.
        /// </summary>
        internal static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileBinary.
        /// </summary>
        internal static string FileBinary {
            get {
                return ResourceManager.GetString("FileBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSource.
        /// </summary>
        internal static string FileSource {
            get {
                return ResourceManager.GetString("FileSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoogleApiKey.
        /// </summary>
        internal static string GoogleApiKey {
            get {
                return ResourceManager.GetString("GoogleApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsOneTimePasswordVerified.
        /// </summary>
        internal static string IsOneTimePasswordVerified {
            get {
                return ResourceManager.GetString("IsOneTimePasswordVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPickupDropAvailable.
        /// </summary>
        internal static string IsPickupDropAvailable {
            get {
                return ResourceManager.GetString("IsPickupDropAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPickUpDropFacilityAvailable.
        /// </summary>
        internal static string IsPickUpDropFacilityAvailable {
            get {
                return ResourceManager.GetString("IsPickUpDropFacilityAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPromotionalEmailRequired.
        /// </summary>
        internal static string IsPromotionalEmailRequired {
            get {
                return ResourceManager.GetString("IsPromotionalEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReviewSubmitted.
        /// </summary>
        internal static string IsReviewSubmitted {
            get {
                return ResourceManager.GetString("IsReviewSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastLoginOn.
        /// </summary>
        internal static string LastLoginOn {
            get {
                return ResourceManager.GetString("LastLoginOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberPlate.
        /// </summary>
        internal static string NumberPlate {
            get {
                return ResourceManager.GetString("NumberPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferCount.
        /// </summary>
        internal static string OfferCount {
            get {
                return ResourceManager.GetString("OfferCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferDescription.
        /// </summary>
        internal static string OfferDescription {
            get {
                return ResourceManager.GetString("OfferDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferDetailsId.
        /// </summary>
        internal static string OfferDetailsId {
            get {
                return ResourceManager.GetString("OfferDetailsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferEndDate.
        /// </summary>
        internal static string OfferEndDate {
            get {
                return ResourceManager.GetString("OfferEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferStartDate.
        /// </summary>
        internal static string OfferStartDate {
            get {
                return ResourceManager.GetString("OfferStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneTimePassword.
        /// </summary>
        internal static string OneTimePassword {
            get {
                return ResourceManager.GetString("OneTimePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverAllRating.
        /// </summary>
        internal static string OverAllRating {
            get {
                return ResourceManager.GetString("OverAllRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PendingForServiceRequestCount.
        /// </summary>
        internal static string PendingForServiceRequestCount {
            get {
                return ResourceManager.GetString("PendingForServiceRequestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PendingServiceCount.
        /// </summary>
        internal static string PendingServiceCount {
            get {
                return ResourceManager.GetString("PendingServiceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinCode.
        /// </summary>
        internal static string PinCode {
            get {
                return ResourceManager.GetString("PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfilePictureAttachmentId.
        /// </summary>
        internal static string ProfilePictureAttachmentId {
            get {
                return ResourceManager.GetString("ProfilePictureAttachmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfilePictureContentType.
        /// </summary>
        internal static string ProfilePictureContentType {
            get {
                return ResourceManager.GetString("ProfilePictureContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfilePictureFileBinary.
        /// </summary>
        internal static string ProfilePictureFileBinary {
            get {
                return ResourceManager.GetString("ProfilePictureFileBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfilePictureFileName.
        /// </summary>
        internal static string ProfilePictureFileName {
            get {
                return ResourceManager.GetString("ProfilePictureFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfilePictureSource.
        /// </summary>
        internal static string ProfilePictureSource {
            get {
                return ResourceManager.GetString("ProfilePictureSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfilePictureUploadedOn.
        /// </summary>
        internal static string ProfilePictureUploadedOn {
            get {
                return ResourceManager.GetString("ProfilePictureUploadedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RatedOn.
        /// </summary>
        internal static string RatedOn {
            get {
                return ResourceManager.GetString("RatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RatedUserEmail.
        /// </summary>
        internal static string RatedUserEmail {
            get {
                return ResourceManager.GetString("RatedUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RatedUserMobileNumber.
        /// </summary>
        internal static string RatedUserMobileNumber {
            get {
                return ResourceManager.GetString("RatedUserMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RatedUserName.
        /// </summary>
        internal static string RatedUserName {
            get {
                return ResourceManager.GetString("RatedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RatedUserProfileId.
        /// </summary>
        internal static string RatedUserProfileId {
            get {
                return ResourceManager.GetString("RatedUserProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RatingDescription.
        /// </summary>
        internal static string RatingDescription {
            get {
                return ResourceManager.GetString("RatingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SenderId.
        /// </summary>
        internal static string SenderId {
            get {
                return ResourceManager.GetString("SenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Already Raised.
        /// </summary>
        internal static string SERVICE_ERROR_01 {
            get {
                return ResourceManager.GetString("SERVICE_ERROR_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceAttachmentId.
        /// </summary>
        internal static string ServiceAttachmentId {
            get {
                return ResourceManager.GetString("ServiceAttachmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDealerBusinessCount.
        /// </summary>
        internal static string ServiceDealerBusinessCount {
            get {
                return ResourceManager.GetString("ServiceDealerBusinessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDeliveredOn.
        /// </summary>
        internal static string ServiceDeliveredOn {
            get {
                return ResourceManager.GetString("ServiceDeliveredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDescription.
        /// </summary>
        internal static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDescriptionId.
        /// </summary>
        internal static string ServiceDescriptionId {
            get {
                return ResourceManager.GetString("ServiceDescriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDescriptionType.
        /// </summary>
        internal static string ServiceDescriptionType {
            get {
                return ResourceManager.GetString("ServiceDescriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDescriptionTypeCode.
        /// </summary>
        internal static string ServiceDescriptionTypeCode {
            get {
                return ResourceManager.GetString("ServiceDescriptionTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDescriptionTypeId.
        /// </summary>
        internal static string ServiceDescriptionTypeId {
            get {
                return ResourceManager.GetString("ServiceDescriptionTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceHistoryCount.
        /// </summary>
        internal static string ServiceHistoryCount {
            get {
                return ResourceManager.GetString("ServiceHistoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceRequestId.
        /// </summary>
        internal static string ServiceRequestId {
            get {
                return ResourceManager.GetString("ServiceRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceRequestNo.
        /// </summary>
        internal static string ServiceRequestNo {
            get {
                return ResourceManager.GetString("ServiceRequestNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceRequestPendingForApprovalCount.
        /// </summary>
        internal static string ServiceRequestPendingForApprovalCount {
            get {
                return ResourceManager.GetString("ServiceRequestPendingForApprovalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceStatusId.
        /// </summary>
        internal static string ServiceStatusId {
            get {
                return ResourceManager.GetString("ServiceStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceStatusTypeCode.
        /// </summary>
        internal static string ServiceStatusTypeCode {
            get {
                return ResourceManager.GetString("ServiceStatusTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceStatusTypeDescription.
        /// </summary>
        internal static string ServiceStatusTypeDescription {
            get {
                return ResourceManager.GetString("ServiceStatusTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceStatusTypeId.
        /// </summary>
        internal static string ServiceStatusTypeId {
            get {
                return ResourceManager.GetString("ServiceStatusTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopAddress.
        /// </summary>
        internal static string ShopAddress {
            get {
                return ResourceManager.GetString("ShopAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopName.
        /// </summary>
        internal static string ShopName {
            get {
                return ResourceManager.GetString("ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopPictureAttachmentId.
        /// </summary>
        internal static string ShopPictureAttachmentId {
            get {
                return ResourceManager.GetString("ShopPictureAttachmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopPictureContentType.
        /// </summary>
        internal static string ShopPictureContentType {
            get {
                return ResourceManager.GetString("ShopPictureContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopPictureFileBinary.
        /// </summary>
        internal static string ShopPictureFileBinary {
            get {
                return ResourceManager.GetString("ShopPictureFileBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopPictureFileName.
        /// </summary>
        internal static string ShopPictureFileName {
            get {
                return ResourceManager.GetString("ShopPictureFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopPictureFileSource.
        /// </summary>
        internal static string ShopPictureFileSource {
            get {
                return ResourceManager.GetString("ShopPictureFileSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopPictureUploadedOn.
        /// </summary>
        internal static string ShopPictureUploadedOn {
            get {
                return ResourceManager.GetString("ShopPictureUploadedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mobile Number or Password.
        /// </summary>
        internal static string SQL_VALIDATION_ERROR_001 {
            get {
                return ResourceManager.GetString("SQL_VALIDATION_ERROR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number already registered.
        /// </summary>
        internal static string SQL_VALIDATION_ERROR_002 {
            get {
                return ResourceManager.GetString("SQL_VALIDATION_ERROR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number already registered.
        /// </summary>
        internal static string SQL_VALIDATION_ERROR_003 {
            get {
                return ResourceManager.GetString("SQL_VALIDATION_ERROR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Old Password.
        /// </summary>
        internal static string SQL_VALIDATION_ERROR_004 {
            get {
                return ResourceManager.GetString("SQL_VALIDATION_ERROR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mobile Number.
        /// </summary>
        internal static string SQL_VALIDATION_ERROR_005 {
            get {
                return ResourceManager.GetString("SQL_VALIDATION_ERROR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid one time password.
        /// </summary>
        internal static string SQL_VALIDATION_ERROR_006 {
            get {
                return ResourceManager.GetString("SQL_VALIDATION_ERROR_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Password not verified.
        /// </summary>
        internal static string SQL_VALIDATION_ERROR_007 {
            get {
                return ResourceManager.GetString("SQL_VALIDATION_ERROR_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id already registered.
        /// </summary>
        internal static string SQL_VALIDATION_ERROR_008 {
            get {
                return ResourceManager.GetString("SQL_VALIDATION_ERROR_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusUpdatedOn.
        /// </summary>
        internal static string StatusUpdatedOn {
            get {
                return ResourceManager.GetString("StatusUpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreDealerBusinessCount.
        /// </summary>
        internal static string StoreDealerBusinessCount {
            get {
                return ResourceManager.GetString("StoreDealerBusinessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadedOn.
        /// </summary>
        internal static string UploadedOn {
            get {
                return ResourceManager.GetString("UploadedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserEmail.
        /// </summary>
        internal static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserMobileNumber.
        /// </summary>
        internal static string UserMobileNumber {
            get {
                return ResourceManager.GetString("UserMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPassword.
        /// </summary>
        internal static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserProfileId.
        /// </summary>
        internal static string UserProfileId {
            get {
                return ResourceManager.GetString("UserProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserProfilePictureId.
        /// </summary>
        internal static string UserProfilePictureId {
            get {
                return ResourceManager.GetString("UserProfilePictureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserQualifier.
        /// </summary>
        internal static string UserQualifier {
            get {
                return ResourceManager.GetString("UserQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTypeCode.
        /// </summary>
        internal static string UserTypeCode {
            get {
                return ResourceManager.GetString("UserTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTypeDescription.
        /// </summary>
        internal static string UserTypeDescription {
            get {
                return ResourceManager.GetString("UserTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTypeId.
        /// </summary>
        internal static string UserTypeId {
            get {
                return ResourceManager.GetString("UserTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WashDealerBusinessCount.
        /// </summary>
        internal static string WashDealerBusinessCount {
            get {
                return ResourceManager.GetString("WashDealerBusinessCount", resourceCulture);
            }
        }
    }
}
